#SPDX-License-Identifier: MIT-0
---
# tasks file for vm_upgate
- name: Verificando Repo por Update/Upgrade
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == "Ubuntu"
