---
    - hosts: all
      remote_user: root
      become: yes
      become_user: root
      order: sorted
      tasks:
      - name: Remove Softwares
        yum:
         name: "{{ packages }}"
         state: absent
        vars:
            packages:
                - cloud-init
                
      - name: Install New Softwares
        yum:
         name: "{{ packages }}"
         state: latest
        vars:
            packages:
                - dialog
                - tree
                - wget
                - tar
                - unzip
                - tcsh
                - vim
                - make
                - gcc
                - dnf
                - autoconf
                - automake
                - epel-release
                - cockpit
                - ipa-client

...


