---
# Configurar Timezone para Sao Paulo
- name: Configurando Timezone para Sao Paulo
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# Copiando o Templates
- name: Configurando Tela de Bem Vindo
  template: src=motd dest=/etc/motd force=yes owner=root group=root

# Instalando Epel CentOS
- name: Instalando Epel-Release
  yum: name=epel-release state=latest

# Instalando Cockpit
- name: Instalando Cockpit
  yum: name=cockpit state=latest
  notify: reiniciar cockpit

...