---
# Gerenciamento de Pacotes e Atualizacao de Sistema Operacional
- name: Atualizacao de Sistema Operacional
  yum: name=* state=latest update_cache=yes

# Instalar Requisitos
- name: Instalacao de Requisitos
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - net-tools
        - vim
        - dkms
        - wget
        - git
        - epel-release
        - ipa-client
        - dialog
        - tar
        - unzip
        - gcc

# Configurar Timezone para Sao Paulo
- name: Configurando Timezone para Sao Paulo
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# Copiando o Templates
- name: Configurando Tela de Bem Vindo
  template: src=motd dest=/etc/motd force=yes owner=root group=root

# Instalando Epel CentOS
- name: Instalando Epel-Release
  yum: name=epel-release state=latest

# Instalando Cockpit
- name: Instalando Cockpit
  yum: name=cockpit state=latest
  notify: reiniciar cockpit

...